### PR TITLE
Create tables #1

### LINKED ISSUE #1: Create Tables & Initial data

### PR DESCRIPTION
**Pull request by Kieren27**
Wrote SQL queries to create tables in the db along with initial data (not yet being utilized). Tables are getting dropped and built properly as seen here: 
image

Closes #1 
Closes #2

### CODE REVIEW

**Review by shruthi-tuplur — APPROVED** [review]
Looks good to me!

**Comment by MtKrc** [comment]
Looks good! Thank you, Kieren!

**Comment by MtKrc** [comment]
Seems impressive! Thank you, Kieren!

**Review by MtKrc — APPROVED** [review]
Looks good!

**Review by raynhlee — COMMENTED** [review]
lgtm

**Review by raynhlee — APPROVED** [review]
lgtm

**Pull request merged**
