### PR TITLE
Reviews #14

### LINKED ISSUE #14: review.js database adapters
Create database adapters for "reviews" table:

- createReview: creates a review for a specific product
- getAllReviews: gets all reviews from "reviews" table
- getReviewByProduct: gets all reviews associated with a specific product
- getReviewByUser: gets all reviews made by a specific user
- getReviewById: gets a review by it's id
- updateReview: updates a review's fields
- deleteReview: deletes a review

### PR DESCRIPTION
**Pull request by shruthi-tuplur**
Wrote database adapter functions for the reviews table

Screen Shot 2023-06-27 at 9 18 03 PM

Closes #14

### CODE REVIEW

**Review by Kieren27 — CHANGES_REQUESTED** [review]
Could you just change [res] in deleteReview to [response] to make it more clear what's being returned?

**Review by Kieren27 — APPROVED** [review]
Good work!

**Review by raynhlee — APPROVED** [review]
lgtm

**Review by MtKrc — APPROVED** [review]
👍

**Pull request closed without merging**
